name = "my-shodan-api"
main = "src/index.js"
compatibility_date = "2025-06-01"

[vars]
ALLOWED_ORIGIN = "https://hunter.arksec.net"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "8c73259fb09b46c597ce47e3d7ceb44f"

[[rate_limiters]]
binding = "API_RATELIMITER"
namespace_id = "3"

[[rate_limiters]]
binding = "LOGIN_RATELIMITER"
namespace_id = "6"
